################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/misc.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_adc.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_aes.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_aes_util.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_comp.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_crc.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dac.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dbgmcu.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dma.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_exti.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_flash.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_flash_ramfunc.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_fsmc.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_gpio.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_i2c.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_iwdg.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_lcd.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_opamp.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_pwr.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_rcc.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_rtc.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_sdio.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_spi.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_syscfg.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_tim.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_usart.c \
H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_wwdg.c 

OBJS += \
./StdPeriph_Driver/misc.o \
./StdPeriph_Driver/stm32l1xx_adc.o \
./StdPeriph_Driver/stm32l1xx_aes.o \
./StdPeriph_Driver/stm32l1xx_aes_util.o \
./StdPeriph_Driver/stm32l1xx_comp.o \
./StdPeriph_Driver/stm32l1xx_crc.o \
./StdPeriph_Driver/stm32l1xx_dac.o \
./StdPeriph_Driver/stm32l1xx_dbgmcu.o \
./StdPeriph_Driver/stm32l1xx_dma.o \
./StdPeriph_Driver/stm32l1xx_exti.o \
./StdPeriph_Driver/stm32l1xx_flash.o \
./StdPeriph_Driver/stm32l1xx_flash_ramfunc.o \
./StdPeriph_Driver/stm32l1xx_fsmc.o \
./StdPeriph_Driver/stm32l1xx_gpio.o \
./StdPeriph_Driver/stm32l1xx_i2c.o \
./StdPeriph_Driver/stm32l1xx_iwdg.o \
./StdPeriph_Driver/stm32l1xx_lcd.o \
./StdPeriph_Driver/stm32l1xx_opamp.o \
./StdPeriph_Driver/stm32l1xx_pwr.o \
./StdPeriph_Driver/stm32l1xx_rcc.o \
./StdPeriph_Driver/stm32l1xx_rtc.o \
./StdPeriph_Driver/stm32l1xx_sdio.o \
./StdPeriph_Driver/stm32l1xx_spi.o \
./StdPeriph_Driver/stm32l1xx_syscfg.o \
./StdPeriph_Driver/stm32l1xx_tim.o \
./StdPeriph_Driver/stm32l1xx_usart.o \
./StdPeriph_Driver/stm32l1xx_wwdg.o 

C_DEPS += \
./StdPeriph_Driver/misc.d \
./StdPeriph_Driver/stm32l1xx_adc.d \
./StdPeriph_Driver/stm32l1xx_aes.d \
./StdPeriph_Driver/stm32l1xx_aes_util.d \
./StdPeriph_Driver/stm32l1xx_comp.d \
./StdPeriph_Driver/stm32l1xx_crc.d \
./StdPeriph_Driver/stm32l1xx_dac.d \
./StdPeriph_Driver/stm32l1xx_dbgmcu.d \
./StdPeriph_Driver/stm32l1xx_dma.d \
./StdPeriph_Driver/stm32l1xx_exti.d \
./StdPeriph_Driver/stm32l1xx_flash.d \
./StdPeriph_Driver/stm32l1xx_flash_ramfunc.d \
./StdPeriph_Driver/stm32l1xx_fsmc.d \
./StdPeriph_Driver/stm32l1xx_gpio.d \
./StdPeriph_Driver/stm32l1xx_i2c.d \
./StdPeriph_Driver/stm32l1xx_iwdg.d \
./StdPeriph_Driver/stm32l1xx_lcd.d \
./StdPeriph_Driver/stm32l1xx_opamp.d \
./StdPeriph_Driver/stm32l1xx_pwr.d \
./StdPeriph_Driver/stm32l1xx_rcc.d \
./StdPeriph_Driver/stm32l1xx_rtc.d \
./StdPeriph_Driver/stm32l1xx_sdio.d \
./StdPeriph_Driver/stm32l1xx_spi.d \
./StdPeriph_Driver/stm32l1xx_syscfg.d \
./StdPeriph_Driver/stm32l1xx_tim.d \
./StdPeriph_Driver/stm32l1xx_usart.d \
./StdPeriph_Driver/stm32l1xx_wwdg.d 


# Each subdirectory must supply rules for building sources it contributes
StdPeriph_Driver/misc.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/misc.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I../../../../../Libraries/STMTouch_Driver/inc -I../../../../../Libraries/STM32L1xx_StdPeriph_Driver/inc -I../../../../../Libraries/CMSIS/Device/ST/STM32L1xx/Include -I../../../../../Utilities/STM32L-DISCOVERY -I../../inc -I../../../../Libraries/CMSIS/Include -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/misc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_adc.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_adc.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_adc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_aes.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_aes.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_aes.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_aes_util.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_aes_util.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_aes_util.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_comp.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_comp.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_comp.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_crc.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_crc.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_crc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_dac.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dac.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_dac.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_dbgmcu.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dbgmcu.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_dbgmcu.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_dma.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dma.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_exti.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_exti.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_exti.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_flash.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_flash.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_flash_ramfunc.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_flash_ramfunc.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_flash_ramfunc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_fsmc.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_fsmc.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_fsmc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_gpio.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_gpio.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_i2c.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_i2c.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_i2c.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_iwdg.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_iwdg.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_iwdg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_lcd.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_lcd.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_lcd.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_opamp.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_opamp.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_opamp.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_pwr.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_pwr.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_pwr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_rcc.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_rcc.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_rcc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_rtc.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_rtc.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_rtc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_sdio.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_sdio.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_sdio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_spi.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_spi.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_spi.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_syscfg.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_syscfg.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_syscfg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_tim.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_tim.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_tim.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_usart.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_usart.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_usart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
StdPeriph_Driver/stm32l1xx_wwdg.o: H:/Documents/Embedded/StdPeriph/STM32L1xx_StdPeriph_Lib_V1.3.1/Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_wwdg.c StdPeriph_Driver/subdir.mk
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_STDPERIPH_DRIVER -DTSLPRM_STM32L1XX_SW_ACQ -DSTM32L1XX_MDP -c -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Utilities/STM32L-DISCOVERY" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STMTouch_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/STM32L1xx_StdPeriph_Driver/inc" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Libraries/CMSIS/Device/ST/STM32L1xx/Include" -I"H:/Documents/Embedded/STM32L-Discovery_FW_Pack_2/STM32L-Discovery_FW_Pack/Projects/AN3413-Current_consumption_touch_sensing/TrueSTUDIO/STM32L152RB(STM32L-Discovery)" -Og -ffunction-sections -fdata-sections -Wall -mlong-calls -Wno-pointer-sign -Wno-missing-braces -Wformat=0 -fstack-usage -MMD -MP -MF"StdPeriph_Driver/stm32l1xx_wwdg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

